site_name: Floras - Flow-based Reactive Test Synthesis for Autonomous Systems
site_url: https://floras.readthedocs.io
theme:
  name: material

nav:
  - Home:
    - Welcome: index.md
    - Installing: installing.md
  - Getting Started:
    - Installation: installing.md
  - API:
    - Automata: automata.md
    - Product: product.md
    - Transition System: transition_system.md
    - Optimization: optimization.md
  - Case Studies:
    - Package Delivery: packagedelivery.md
  - Contributing:
    - Contributing: contributing.md

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

copyright: >
  Copyright &copy; 2024 - 2025 Caltech
