---
# configuration for GitHub Actions
name: flowsynth tests
on:
    push:
    pull_request:

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: [
                    '3.10',
                ]
        steps:
            - uses: actions/checkout@v4
            - uses: pdm-project/setup-pdm@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: true
            - name: Setup testing environment
              run: |
                sudo apt update
                sudo apt install -y libgraphviz-dev
            - name: Install Python dependencies
              run: |
                pdm install
            - name: Build and install Spot
              run: |
                pdm run python get_spot.py
            - name: Run tests
              run: |
                pdm run pytest -v tests
